
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

//
//  SimpleAudioPlayerEventSink.h
//  Pods
//
//  Created by 汪洋 on 2024/3/1.
//

#import <Foundation/Foundation.h>
#import <Flutter/Flutter.h>

@interface SimpleAudioPlayerEventSink : NSObject <FlutterStreamHandler>

@property (nonatomic, copy) FlutterEventSink event;

@end
