name: simple_audio_player
description: A simple audio player for Flutter.
version: 0.0.6
homepage: https://github.com/WangYng
repository: https://github.com/WangYng/simple_audio_player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.github.wangyng.simple_audio_player
        pluginClass: SimpleAudioPlayerPlugin
      ios:
        pluginClass: SimpleAudioPlayerPlugin
