
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

package io.github.wangyng.simple_audio_player;

import io.flutter.plugin.common.EventChannel;

public class SimpleAudioPlayerEventSink {
    EventChannel.EventSink event;
}
